// Created by iWeb 3.0.4 local-build-20121209

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,241),url:'2_Cheese,_Bog_and_Whale_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_9.png'},{rect:new IWRect(2,-2,180,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_10.png'},{rect:new IWRect(182,-2,4,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_11.png'},{rect:new IWRect(182,2,4,241),url:'2_Cheese,_Bog_and_Whale_files/stroke_12.png'},{rect:new IWRect(182,243,4,5),url:'2_Cheese,_Bog_and_Whale_files/stroke_13.png'},{rect:new IWRect(2,243,180,5),url:'2_Cheese,_Bog_and_Whale_files/stroke_14.png'},{rect:new IWRect(-2,243,4,5),url:'2_Cheese,_Bog_and_Whale_files/stroke_15.png'}],new IWSize(184,245)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,178),url:'2_Cheese,_Bog_and_Whale_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_1.png'},{rect:new IWRect(2,-2,221,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_2.png'},{rect:new IWRect(223,-2,4,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_3.png'},{rect:new IWRect(223,2,4,178),url:'2_Cheese,_Bog_and_Whale_files/stroke_4.png'},{rect:new IWRect(223,180,4,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_5.png'},{rect:new IWRect(2,180,221,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_6.png'},{rect:new IWRect(-2,180,4,4),url:'2_Cheese,_Bog_and_Whale_files/stroke_7.png'}],new IWSize(225,182))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('2_Cheese,_Bog_and_Whale_files/2_Cheese,_Bog_and_WhaleMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');fixupIECSS3Opacity('id4');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
