// Created by iWeb 3.0.4 local-build-20121209

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,214),url:'13_Chateau_or_Chateaux_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'13_Chateau_or_Chateaux_files/stroke_1.png'},{rect:new IWRect(2,-2,287,4),url:'13_Chateau_or_Chateaux_files/stroke_2.png'},{rect:new IWRect(289,-2,4,4),url:'13_Chateau_or_Chateaux_files/stroke_3.png'},{rect:new IWRect(289,2,4,214),url:'13_Chateau_or_Chateaux_files/stroke_4.png'},{rect:new IWRect(289,216,4,5),url:'13_Chateau_or_Chateaux_files/stroke_5.png'},{rect:new IWRect(2,216,287,5),url:'13_Chateau_or_Chateaux_files/stroke_6.png'},{rect:new IWRect(-2,216,4,5),url:'13_Chateau_or_Chateaux_files/stroke_7.png'}],new IWSize(291,218)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,177),url:'13_Chateau_or_Chateaux_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'13_Chateau_or_Chateaux_files/stroke_9.png'},{rect:new IWRect(2,-2,376,4),url:'13_Chateau_or_Chateaux_files/stroke_10.png'},{rect:new IWRect(378,-2,5,4),url:'13_Chateau_or_Chateaux_files/stroke_11.png'},{rect:new IWRect(378,2,5,177),url:'13_Chateau_or_Chateaux_files/stroke_12.png'},{rect:new IWRect(378,179,5,4),url:'13_Chateau_or_Chateaux_files/stroke_13.png'},{rect:new IWRect(2,179,376,4),url:'13_Chateau_or_Chateaux_files/stroke_14.png'},{rect:new IWRect(-2,179,4,4),url:'13_Chateau_or_Chateaux_files/stroke_15.png'}],new IWSize(380,181))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('13_Chateau_or_Chateaux_files/13_Chateau_or_ChateauxMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');fixupIECSS3Opacity('id4');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
