// Created by iWeb 3.0.4 local-build-20121209

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-6,6,11,244),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_16.png'},{rect:new IWRect(-7,-7,12,13),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_17.png'},{rect:new IWRect(5,-4,180,10),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_18.png'},{rect:new IWRect(185,-6,10,12),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_19.png'},{rect:new IWRect(185,6,9,244),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_20.png'},{rect:new IWRect(185,250,10,10),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_21.png'},{rect:new IWRect(5,250,180,8),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_22.png'},{rect:new IWRect(-8,250,13,7),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_23.png'}],new IWSize(190,253)),stroke_1:new IWStrokeParts([{rect:new IWRect(-6,5,10,292),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_8.png'},{rect:new IWRect(-6,-7,10,12),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_9.png'},{rect:new IWRect(4,-5,191,10),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_10.png'},{rect:new IWRect(195,-5,12,10),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_11.png'},{rect:new IWRect(195,5,10,292),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_12.png'},{rect:new IWRect(195,297,11,9),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_13.png'},{rect:new IWRect(4,297,191,8),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_14.png'},{rect:new IWRect(-10,297,14,9),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_15.png'}],new IWSize(200,300)),stroke_0:new IWStrokeParts([{rect:new IWRect(-5,6,10,239),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke.png'},{rect:new IWRect(-6,-5,11,11),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_1.png'},{rect:new IWRect(5,-4,390,10),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_2.png'},{rect:new IWRect(395,-6,10,12),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_3.png'},{rect:new IWRect(395,6,9,239),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_4.png'},{rect:new IWRect(395,245,11,11),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_5.png'},{rect:new IWRect(5,245,390,9),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_6.png'},{rect:new IWRect(-13,245,18,11),url:'23_In_pursuit_of_the_perfect_pour..._files/stroke_7.png'}],new IWSize(400,250))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('23_In_pursuit_of_the_perfect_pour..._files/23_In_pursuit_of_the_perfect_pour...Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');fixupAllIEPNGBGs();Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');fixupIECSS3Opacity('id3');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
