// Created by iWeb 3.0.4 local-build-20121209

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,296),url:'15_First_Casualty_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'15_First_Casualty_files/stroke_9.png'},{rect:new IWRect(2,-2,221,4),url:'15_First_Casualty_files/stroke_10.png'},{rect:new IWRect(223,-2,4,4),url:'15_First_Casualty_files/stroke_11.png'},{rect:new IWRect(223,2,4,296),url:'15_First_Casualty_files/stroke_12.png'},{rect:new IWRect(223,298,4,4),url:'15_First_Casualty_files/stroke_13.png'},{rect:new IWRect(2,298,221,4),url:'15_First_Casualty_files/stroke_14.png'},{rect:new IWRect(-2,298,4,4),url:'15_First_Casualty_files/stroke_15.png'}],new IWSize(225,300)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,204),url:'15_First_Casualty_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'15_First_Casualty_files/stroke_1.png'},{rect:new IWRect(2,-2,430,4),url:'15_First_Casualty_files/stroke_2.png'},{rect:new IWRect(432,-2,4,4),url:'15_First_Casualty_files/stroke_3.png'},{rect:new IWRect(432,2,4,204),url:'15_First_Casualty_files/stroke_4.png'},{rect:new IWRect(432,206,4,4),url:'15_First_Casualty_files/stroke_5.png'},{rect:new IWRect(2,206,430,4),url:'15_First_Casualty_files/stroke_6.png'},{rect:new IWRect(-2,206,4,4),url:'15_First_Casualty_files/stroke_7.png'}],new IWSize(434,208))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('15_First_Casualty_files/15_First_CasualtyMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');fixupIECSS3Opacity('id5');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
