// Created by iWeb 3.0.4 local-build-20121209

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,196),url:'5_Her_Majestys_Secret_Service_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'5_Her_Majestys_Secret_Service_files/stroke_1.png'},{rect:new IWRect(2,-2,416,4),url:'5_Her_Majestys_Secret_Service_files/stroke_2.png'},{rect:new IWRect(418,-2,4,4),url:'5_Her_Majestys_Secret_Service_files/stroke_3.png'},{rect:new IWRect(418,2,4,196),url:'5_Her_Majestys_Secret_Service_files/stroke_4.png'},{rect:new IWRect(418,198,4,4),url:'5_Her_Majestys_Secret_Service_files/stroke_5.png'},{rect:new IWRect(2,198,416,4),url:'5_Her_Majestys_Secret_Service_files/stroke_6.png'},{rect:new IWRect(-2,198,4,4),url:'5_Her_Majestys_Secret_Service_files/stroke_7.png'}],new IWSize(420,200)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,221),url:'5_Her_Majestys_Secret_Service_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'5_Her_Majestys_Secret_Service_files/stroke_9.png'},{rect:new IWRect(2,-2,296,4),url:'5_Her_Majestys_Secret_Service_files/stroke_10.png'},{rect:new IWRect(298,-2,4,4),url:'5_Her_Majestys_Secret_Service_files/stroke_11.png'},{rect:new IWRect(298,2,4,221),url:'5_Her_Majestys_Secret_Service_files/stroke_12.png'},{rect:new IWRect(298,223,4,4),url:'5_Her_Majestys_Secret_Service_files/stroke_13.png'},{rect:new IWRect(2,223,296,4),url:'5_Her_Majestys_Secret_Service_files/stroke_14.png'},{rect:new IWRect(-2,223,4,4),url:'5_Her_Majestys_Secret_Service_files/stroke_15.png'}],new IWSize(300,225))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('5_Her_Majestys_Secret_Service_files/5_Her_Majestys_Secret_ServiceMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');fixupIECSS3Opacity('id4');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
