// Created by iWeb 3.0.4 local-build-20121209

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,178),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_9.png'},{rect:new IWRect(2,-2,313,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_10.png'},{rect:new IWRect(315,-2,4,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_11.png'},{rect:new IWRect(315,2,4,178),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_12.png'},{rect:new IWRect(315,180,4,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_13.png'},{rect:new IWRect(2,180,313,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_14.png'},{rect:new IWRect(-2,180,4,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_15.png'}],new IWSize(317,182)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,138),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_1.png'},{rect:new IWRect(2,-2,186,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_2.png'},{rect:new IWRect(188,-2,4,4),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_3.png'},{rect:new IWRect(188,2,4,138),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_4.png'},{rect:new IWRect(188,140,4,5),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_5.png'},{rect:new IWRect(2,140,186,5),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_6.png'},{rect:new IWRect(-2,140,4,5),url:'11_Sans_Plomb_et_sans_fin_des_peages_files/stroke_7.png'}],new IWSize(190,142))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('11_Sans_Plomb_et_sans_fin_des_peages_files/11_Sans_Plomb_et_sans_fin_des_peagesMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');fixupIECSS3Opacity('id4');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
