// Created by iWeb 3.0.4 local-build-20121209

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,296),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_9.png'},{rect:new IWRect(2,-2,221,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_10.png'},{rect:new IWRect(223,-2,4,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_11.png'},{rect:new IWRect(223,2,4,296),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_12.png'},{rect:new IWRect(223,298,4,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_13.png'},{rect:new IWRect(2,298,221,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_14.png'},{rect:new IWRect(-2,298,4,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_15.png'}],new IWSize(225,300)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,207),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_1.png'},{rect:new IWRect(2,-2,550,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_2.png'},{rect:new IWRect(552,-2,4,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_3.png'},{rect:new IWRect(552,2,4,207),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_4.png'},{rect:new IWRect(552,209,4,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_5.png'},{rect:new IWRect(2,209,550,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_6.png'},{rect:new IWRect(-2,209,4,4),url:'30_The_Centre_of_the_Cultural_Universe_files/stroke_7.png'}],new IWSize(554,211))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('30_The_Centre_of_the_Cultural_Universe_files/30_The_Centre_of_the_Cultural_UniverseMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../../../Media/transparent.gif');fixupIECSS3Opacity('id4');BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
